[package]
name = "intellectual"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
clap = "3.2.21"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
reqwest = "0.11.11"

[profile.release]
strip = true
lto = true
