[package]
name = "intellectual"
version = "0.2.0"
license = "AGPL-3.0"
repository = "https://github.com/Insprill/intellectual"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
askama = { version = "0.11.1", default-features = false }
awc = { version = "3.0.1", default-features = false, features = ["rustls", "compress-gzip"] }
clap = "4.0.27"
futures = "0.3.25"
include_dir = "0.7.3"
log = "0.4.17"
scraper = "0.13.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
simplelog = "0.12.0"
urlencoding = "2.1.2"

[profile.release]
strip = true
lto = true
