[package]
name = "intellectual"
version = "0.1.0"
license = "AGPL-3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.2.1"
askama = { version = "0.11.1", default-features = false }
clap = "4.0.26"
futures = "0.3.25"
log = "0.4.17"
reqwest = "0.11.13"
scraper = "0.13.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
simplelog = "0.12.0"

[profile.release]
strip = true
lto = true
