services:
  intellectual:
    image: insprill/intellectual:latest # Switch to 'develop' to use the latest git version. May be unstable!
    restart: always
    ports:
      - 8080:8080 # Use `127.0.0.1:8080:8080` if you're using a reverse proxy on the same machine.
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080 || exit 1
      interval: 1m
      timeout: 5s
