services:
  intellectual:
    image: insprill/intellectual:latest
    container_name: intellectual
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080 || exit 1
      interval: 5m
      timeout: 5s
