name: Bug Report
description: Report a bug with Intellectual.
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Are you using the latest version of Intellectual?
      description: Please make sure you're using the latest version of Intellectual as it's possible your issue has already been fixed.
      options:
        - label: I am using the latest version of Intellectual.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Describe the bug in as much detail as you can.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
