blank_issues_enabled: false

contact_links:
  - name: Discussion Board
    url: https://github.com/Insprill/intellectual/discussions
    about: Have a question? Look through the existing discussions, or create a new one!
