name: Docker Build

on: [ push, pull_request ]

env:
  DOCKER_IMAGE: insprill/intellectual
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup act
        run: "sudo chown runner:docker /var/run/docker.sock"
        if: ${{ env.ACT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ !env.ACT && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        if: $${{ !env.ACT && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKER_IMAGE }}
          enable-url-completion: true

      - name: Set Environment Variables
        run: |
          echo "IN_IS_GIT=true" >> .env
          echo "IN_GIT_HASH=$(git rev-parse --short HEAD)" >> .env
          echo "IN_GIT_DIRTY=$([[ -n $(git status --porcelain) ]] && echo true || echo false)" >> .env
          echo "IN_GIT_TAG=$(git describe --tags --exact-match)" >> .env
          echo "IN_GIT_TAGGED=$([[ -n $(git describe --tags --exact-match) ]] && echo true || echo false)" >> .env
          echo "IN_GIT_REMOTE_URL=$(git remote get-url origin)" >> .env

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: . # Required for running with act
          push: ${{ !env.ACT && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ startsWith(github.ref, 'refs/tags/v') && 'latest' || 'develop' }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
