name: Build

on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          target: ${{ matrix.target }}
          toolchain: stable

      - name: Run Clippy
        uses: actions-rs/clippy@v1
        with:
          args: -- -D warnings

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Intellectual-${{ matrix.target }}
          path: target/release/intellectual${{ matrix.suffix }}
