name: Build

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            suffix: ''
            name: macOS
          - os: ubuntu-latest
            suffix: ''
            name: Linux
          - os: windows-latest
            suffix: .exe
            name: Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.name }}

      - name: Check Code Style
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Intellectual-${{ matrix.name }}
          path: target/release/intellectual${{ matrix.suffix }}
