name: Build

on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            suffix: ''
          - os: ubuntu-latest
            suffix: ''
          - os: windows-latest
            suffix: .exe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: stable

      - name: Setup Cache
        uses: Swatinem/rust-cache@v1

      - name: Install Linux Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install -y libssl-dev

      - name: Check Code Style
        uses: actions-rs/clippy@master
        with:
          args: -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Make Linux Binary Executable
        if: ${{ runner.os == 'Linux' }}
        run: chmod +x target/release/intellectual

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Intellectual-${{ matrix.target }}
          path: target/release/intellectual${{ matrix.suffix }}
